# Generated by Django 5.2.5 on 2025-08-07 01:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='부스명', max_length=100)),
                ('code', models.CharField(help_text='부스 고유 코드 (QR에 포함)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='부스 설명')),
                ('is_active', models.BooleanField(default=True, help_text='부스 활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '체험부스',
                'verbose_name_plural': '체험부스들',
                'db_table': 'booths',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='참여자 고유 식별자 (UUID)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='참여자 생성 시간')),
                ('is_completed', models.BooleanField(default=False, help_text='5개 부스 완주 여부')),
                ('completed_at', models.DateTimeField(blank=True, help_text='미션 완료 시간', null=True)),
            ],
            options={
                'verbose_name': '참여자',
                'verbose_name_plural': '참여자들',
                'db_table': 'participants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StampRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamped_at', models.DateTimeField(auto_now_add=True, help_text='스탬프 획득 시간')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='스탬프 획득 시 IP 주소', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='사용자 브라우저 정보')),
                ('booth', models.ForeignKey(help_text='체험부스', on_delete=django.db.models.deletion.CASCADE, related_name='stamp_records', to='stamps.booth')),
                ('participant', models.ForeignKey(help_text='참여자', on_delete=django.db.models.deletion.CASCADE, related_name='stamp_records', to='stamps.participant')),
            ],
            options={
                'verbose_name': '스탬프 기록',
                'verbose_name_plural': '스탬프 기록들',
                'db_table': 'stamp_records',
                'ordering': ['-stamped_at'],
                'unique_together': {('participant', 'booth')},
            },
        ),
    ]
